### ISSUE TITLE
Feature request: pin a specific configuration for a workspace?

### ISSUE THREAD

**Issue by glasser** [wasamasa/eyebrowse#101]
I really like the UX of eyebrowse — the overall experience of having a few workspaces, easy swap commands, a great mode-line indicator.

The one thing I'm really missing, though, is a way to say (dynamically) "this is what workspace 1 should look like", and have an easy way to revert it to that configuration if it gets far from there.

I'm not asking for a way to save configurations across restarts, or to set up configurations from Elisp — just a way to hit a key that says "this is the 'right' version of this workspace", and to later hit another key to snap back to it.

`wconf` mode has this feature and so I've switched to it from `eyebrowse`, but there's a lot of good stuff in `eyebrowse` that's missing from `wconf`.

Does anyone else have this desire? Have you fixed it in some other way?

(Honestly maybe all I really want is a better modeline/keystroke UI around the built in window config register commands.)

**Comment by wasamasa** [comment]
I just use `winner-mode` and undo the configuration a few times if something ever messes it up. It's very simple and easier to do than remembering to set a checkpoint, then going back to it when needed.

Another approach is to copy a window config to a different slot (by visiting an unoccupied one), then once the current one has been messed up closing it, switching to the pristine one, then back to the closed one.
