### ISSUE TITLE
How to get the current workspace number?

### ISSUE THREAD

**Issue by m-cat** [wasamasa/eyebrowse#103]
I may be missing something, but it's not clear to me how to get the number and/or tag of the current workspace. I know spaceline does it, but I don't have the time to delve into its source code. I feel like there should be a variable that stores this info but I can't find it.

**Comment by wasamasa** [comment]
There's no variable for this indeed as it's information stored per frame. There's no official API either, I neglected to introduce one back then and by the time spaceline just used the internal API it was too late to fix this mistake.

Anyway, you should be fine with using `(eyebrowse--get 'current-slot)`. While this may change, it's rather unlikely as this package is pretty much in bugfix mode.
