### ISSUE TITLE
Feature request: optionally drop windows for deleted buffers

### ISSUE THREAD

**Issue by whirm** [wasamasa/eyebrowse#106]
I often have compilation or other temporary buffers when quitting emacs which means that when I start it up again I get a bunch of windows with scratch buffers.

It would be great to be able to set a flag so eyebrowse drops windows containing deleted buffers instead of replacing them with the scratch buffer.

Thanks!

**Comment by wasamasa** [comment]
This is what happened before I fixed this behavior because it drove me mad to not see why windows were randomly disappearing, so no.

**Comment by whirm** [comment]
Just to be clear, I'm talking about restore time only.

Can't we have a disabled by default custom option? 

Would  you accept a PR introducing this feature?

Cheers,

**Comment by wasamasa** [comment]
No
