### ISSUE TITLE
Only create buffers in eyebrowse-current-slot when restoring emacs desktop.

### ISSUE THREAD

**Issue by yanghaoxie** [wasamasa/eyebrowse#107]
`Desktop-save-mode` can be used to restore the last saved desktop, IMHO, it restores all saved buffers. However, the drawback is it will be pretty slow if you have many buffer opened.

Therefore, I wonder whether it is possible that we make `desktop` only restore buffers in `eyebrowse-current-slot`, and restore buffers in another `slot` only when we switch to it.

**Comment by wasamasa** [comment]
I'm not sure why you're asking me that. This issue tracker is about eyebrowse, not desktop.el.  I don't use it, I merely mention it in the README as a way to restore window configurations.  There are better venues for figuring out how it works, like its documentation, the `#emacs` channel, Reddit, mailing lists, etc.

**Comment by yanghaoxie** [comment]
Thanks for your replay!
I will try other methods.
