### ISSUE TITLE
question: switch to window config by tag name

### ISSUE THREAD

**Issue by mcraveiro** [wasamasa/eyebrowse#112]
Hi,

Thank you very much for an amazing tool. I have a question related to switching configs by tag name. I am using helm. At present, when I type the tag name I get no matches; but if I type the config number then I get a match. For example, let's say I have a config number 14 called ```sql```. I cannot get it selected by typing ```sq``` but if I type ```14:sq``` it matches. Is this expected or have I somehow done something to my helm configuration?

Many thanks for your time.

Marco

**Comment by wasamasa** [comment]
I cannot reproduce this with helm, so it's most likely your config. Unless you manage providing a set of minimal reproduction steps, I don't consider this a bug.

**Comment by mcraveiro** [comment]
Thanks for your help. I will look into the configuration.
