### ISSUE TITLE
Document how to pre-configure default windows

### ISSUE THREAD

**Issue by FrostyX** [wasamasa/eyebrowse#113]
I would like to pre-configure my default windows in `init.el`. I use eyebrowse so I can work on multiple projects at the same time. And they don't change, so I would like to have something like e.g.

    (setq eyebrowse-default-windows
      '((1 . "stuff")
        (2 . "someworkproject")
        (3 . "blog")))

is it possible now? Can this use-case be documented, please?

**Comment by wasamasa** [comment]
There is no such support built-in. What I've tested successfully is persistence using desktop.el, which is mentioned in the README. That way you can save and restore your frame's window configurations.
