### ISSUE TITLE
Make window configs "taggable"

### ISSUE THREAD

**Issue by wasamasa** [wasamasa/eyebrowse#15]
The internal data structure consists of elements which are a list containing the id, window config and point. The id is displayed as is in the mode line. It would be better to separate and add a caption which is displayed and defaults to `(number-to-string id)`. That would allow renaming it interactively.

**Comment by wasamasa** [comment]
I've had an idea how to keep format strings simple.

A tag is an empty string by default, but can be set and turn into a non-empty string. To avoid introducing format spec codes with conditionals, I've decided to just use two customizable format strings instead, one that is used when a tag is present and another one if it isn't. So, assuming the available format codes are `%s` (slot), `%t` (tag) and `%b` (buffer), using `"%s - %t"` and `"%s"` would approximate i3 style.

While I'm at it, an extra customizable format string for the currently active item might be cool (to mark it up similiar to tmux).

**Comment by braham-snyder** [comment]
@wasamasa any chance you'd be interested in making (or open to someone else making) `eyebrowse-switch-to-window-config` behave like `find-file`, such that inputting a non-matching tag creates a new window config with that tag? If so, I can create a new issue for it if you'd like.

Thanks for `eyebrowse`!

**Comment by wasamasa** [comment]
@braham-snyder Sure, why not.  I think you mean slot instead of tag though, as the command is currently reading in a slot.

**Comment by braham-snyder** [comment]
got it--made the new issue here: https://github.com/wasamasa/eyebrowse/issues/58
