### ISSUE TITLE
Add an option for an "empty" window config for unused workspaces

### ISSUE THREAD

**Issue by Benaiah** [wasamasa/eyebrowse#23]
In i3wm, if you switch to a workspace you haven't put a window on yet, it displays nothing. In the current eyebrowse implementation, when you switch to a workspace you haven't yet done anything with, it assigns whatever your current window config is to that workspace. While this is a workflow that makes sense, it would allow for greater consistency with i3 if there was an "empty" window config that would populate each workspace that you haven't used. This could just be an option, eg. `(setq eyebrowse-empty-workspaces t)` or something to that effect. For the actual contents of the default window config, since Emacs does not support not actually displaying anything, I propose a single window displaying the `*scratch*` buffer.

**Comment by wasamasa** [comment]
Feel free to test this by setting `eyebrowse-new-workspace` to `t`. It also supports specifying a buffer name to switch to or function name to funcall.
