### ISSUE TITLE
Clean state when switching to a new window configuration

### ISSUE THREAD

**Issue by tuhdo** [wasamasa/eyebrowse#25]
In `i3`, whenever you switch to a new workspace, it starts with a blank frame with default wallpaper. It would be useful when we switch workspace, the window is reset to a default buffer so it's more obvious for first time users and is closer to `i3` or Vim's tabs. This could be made into a user option to choose an initial buffer (i.e. `*scratch*`) or if `nil`, keeps current window configuration when switched.

**Comment by daviwil** [comment]
+1.  I'd say you could have a blank workspace as the default or duplicate the current workspace by hitting the prefix key before changing to the new workspace.

**Comment by tuhdo** [comment]
@daviwil I did some workaround with the hook `eyebrowse-post-window-switch-hook`:

```elisp
(defvar spacemacs-slot nil)
(defun spacemacs-eyebrowe-maybe-switch-home ()
  (interactive "P")
  (unless (member slot spacemacs-slot)
    (push slot spacemacs-slot)
    (delete-other-windows)
    (spacemacs/home)))
(add-hook 'eyebrowse-post-window-switch-hook 'spacemacs-eyebrowe-maybe-switch-home)
````

So now if you switch to a new config and the config is not available, just go home.

**Comment by tuhdo** [comment]
@wasamasa maybe you could add this simple approach before any major refactoring? This could be easily extended to include tags for each slot using pairs instead of just storing slot numbers. With that, we also solve this issue: https://github.com/wasamasa/eyebrowse/issues/15

Also, an option could be added for users to select between the two behavior.

**Comment by wasamasa** [comment]
This is basically the same as #23, except that this one has sample code attached to it :D

**Comment by wasamasa** [comment]
I've implemented #23 and added customization options as suggested in here for picking an arbitrary buffer name to switch to or alternativelly, calling a function for initialization.

@daviwil: Are you still interested in making a prefix argument unconditionally cloning a workspace? If yes, please open a new issue for it and I'll close this one.

**Comment by daviwil** [comment]
Nah, was just an idea.  I prefer being able to just get a clean slate anyway, so the new change is great.  Thanks a lot!

**Comment by tuhdo** [comment]
Yes thanks for @wasamasa this is a great feature. I've updated my PR to use switch to Spacemacs home when a new workspace is created: https://github.com/syl20bnr/spacemacs/pull/1384
