### ISSUE TITLE
When eyebrowse-mode is enabled, it should automatically create a default workspace

### ISSUE THREAD

**Issue by tuhdo** [wasamasa/eyebrowse#27]
The idea is to make sure that when enabled, we always have a workspace, so creating new workspace won't delete current window configuration. Right now when first creating a new workspace after `eyebrowse-mode` is enabled, it deletes the current window configuration without a way to go back.

I suggest that when `eyebrowse-mode` is initialized, the total number of workspaces is 0 (none exists yet), and for that reason it uses the current window configuration and create a new workspace with workspace number 1. So later we create workspace number 2, number 1 is not deleted.

**Comment by tuhdo** [comment]
Currently I have to do it like this to keep default workspace 1:

```elisp
(eyebrowse-switch-to-window-config-0)
(eyebrowse-switch-to-window-config-1)
(eyebrowse-switch-to-window-config-0)
(eyebrowse-close-window-config)
```

Otherwise when you create any new workspace, number 1 is always deleted.

**Comment by wasamasa** [comment]
Hmm, looks like a regression from the most recent changes.

**Comment by wasamasa** [comment]
That was easier to fix compared to introducing the previous feature.
