### ISSUE TITLE
Slot 1 repeated when using desktop-save mode

### ISSUE THREAD

**Issue by srubben** [wasamasa/eyebrowse#28]
When desktop-save-mode is enabled, the first slot is duplicated when emacs quits. This leads to a modeline which show [1, 1, 1, 1, 2] for instance.

If you look at .emacs.desktop, you can see in desktop-saved-frameset something like this:

    (setq desktop-saved-frameset  <snip>  (eyebrowse-last-slot . 1) (eyebrowse-current-slot . 1) (eyebrowse-window-configs (1 "Unprintable entity" 151) (1 "Unprintable entity" 174) (1 "Unprintable entity" 174) (2 "Unprintable entity" 77)) 

and so on.

I've started from a new .emacs.d (emacs 24.5), with only this in init.el:

    (desktop-save-mode t)

and only eyebrowse installed from melpa.

**Comment by wasamasa** [comment]
I could fix this specific bug, however this will not make desktop.el restore configurations properly since persistence is not supported at all.  See #24 for more details and a possible remedy.
