### ISSUE TITLE
modeline indicator duplicated after loading themes

### ISSUE THREAD

**Issue by mistnim** [wasamasa/eyebrowse#29]
I use fedora 21, with emacs 24.4.1(from fedora repository) and i3 as a window manager.

This is what happens: http://i.imgur.com/cjfpdEb.png
(it keeps duplicating itself everytime you load a theme)

**Comment by wasamasa** [comment]
Apparently it's possible to add another indicator (and re-initialize) by enabling the mode non-interactively since its code does not check whether an indicator was already present. I could fix this, however this leaves the question how you were able to do that by merely loading a theme.

**Comment by wasamasa** [comment]
Please confirm and close this ticket if this change fixes your specific problem.
