### ISSUE TITLE
eyebrowse--load-window-config: Wrong type argument: window-configuration-p, "Unprintable entity"

### ISSUE THREAD

**Issue by tuhdo** [wasamasa/eyebrowse#31]
To reproduce:

- Save desktop with `desktop-save`.
- Close Emacs and load desktop with `desktop-read`.
- Error happens.

**Comment by wasamasa** [comment]
This is to be expected as window configurations are opaque objects and therefore not serializable.  I'm a bit surprised though that desktop.el doesn't just ignore saving variables it cannot possibly restore.

See #24 for a possible fix.
