### ISSUE TITLE
eyebrowse-switch-to-window-config with tag

### ISSUE THREAD

**Issue by rphillips** [wasamasa/eyebrowse#32]
The new tagging feature is awesome. When I call `eyebrowse-switch-to-window-config` without any arguments the candidates are filled in to the current one automatically. Perhaps this is a spacemacs or helm-ism. After I backspace, then all the candiates appear.

**Comment by rphillips** [comment]
![image](https://cloud.githubusercontent.com/assets/1963/8039489/b9b989da-0dcf-11e5-85bb-ece73cc4dc59.png)

![image](https://cloud.githubusercontent.com/assets/1963/8039498/c6e2c0ae-0dcf-11e5-90a3-93261547e60b.png)

**Comment by wasamasa** [comment]
It should suggest the *last* one to give you the opportunity to switch back to it easily. Can you confirm that when having more than one workspace open?

**Comment by wasamasa** [comment]
Anyways, if that's really it, then I guess I should rethink this default and turn it into a customizable option at the very least.

**Comment by wasamasa** [comment]
I nuked it completely as there's already a command, keybind and customizable to switch to the last window config.

**Comment by rphillips** [comment]
Yeah. That was it. I think this tweak makes sense. Thank you!
