### ISSUE TITLE
Feature request: create new config

### ISSUE THREAD

**Issue by adouzzy** [wasamasa/eyebrowse#33]
Instead of C-c C-w numbers, can we have a command just create a new config?
Plus, the bold font of the active config is not very noticeable. May be you can add some brackets as an option? or change colors.
Thanks

**Comment by wasamasa** [comment]
The numbers are merely defaults. Switching to a yet unused slot creates the new window config at it. You can use `eyebrowse-switch-to-window-config` with a numerical prefix argument to specify that slot number (or `eyebrowse-next-window-config` with a numerical prefix).  I've pushed an update to bind that command to `C-c C-w .`, so with that `C-9001 C-c C-w .` will create a new window config at slot 9001.

As for highlighting, feel free to customize `eyebrowse-mode-line-active`, it's currently set to the `mode-line-emphasis` face (which you could customize instead if you wish as that's used by more than just eyebrowse) which is set up by your current theme. Mine for example makes it bright, yours apparently bold. As for the option to change the format of the current slot in the modeline indicator, I haven't implemented such a customizable yet. If you still wish for it, create a new ticket specifically for that feature and I'll implement a format string for both active and inactive slots.

**Comment by adouzzy** [comment]
@wasamasa Awesome! Thanks.

**Comment by wasamasa** [comment]
Please close this ticket once you've decided on the last part.
