### ISSUE TITLE
Feature request: Add 'Close workspace?' prompt

### ISSUE THREAD

**Issue by kovrik** [wasamasa/eyebrowse#35]
Add a variable like **eyebrowse-close-window-config-prompt**.
Default value is **nil**.
If set to **t** then ask user to confirm closing window config.

Use case:

**eyebrowse-close-window-config-prompt** is set to **t**.
User executes **eyebrowse-close-window-config**.
Message appears in echo area: *Are you sure you want to close [current] workspace <tag>? (Y or N)*.
If user answers N, then nothing happens.
If user answers Y, then close workspace.

**Comment by wasamasa** [comment]
Sounds good to me. Note that there is a Vim command for closing tabs with similar behaviour, this functionality could be reused for that once I start working on #22.

**Comment by kovrik** [comment]
I changed my local eyebrowse.el as follows:
--------------------------------------------------------------------------------
169a160,165
> (defcustom eyebrowse-close-window-config-prompt nil
>   "Ask user for confirmation when closing workspaces?
> If t, ask for confirmation on workspace close."
>   :type 'boolean
>   :group 'eyebrowse)
> 
363c359,361
<     (when (> (length window-configs) 1)
---
>     (when (and (> (length window-configs) 1)
>                (or (not eyebrowse-close-window-config-prompt)
>                    (y-or-n-p "Close current workspace?")))
--------------------------------------------------------------------------------

**Comment by kovrik** [comment]
Wow, that was fast :)
Thank you!

**Comment by wasamasa** [comment]
Thank you, too, I've mostly adapted your posted patch for it.
