### ISSUE TITLE
eyebrowse-mode-line-inactive face not used

### ISSUE THREAD

**Issue by Dickby** [wasamasa/eyebrowse#37]
Hi,
I tried to edit the eyebrowse-mode-line-inactive face, but it changes nothing, I searched for the keyword in the eyebrowse directory and found only the defface definition.
Thanks

**Comment by wasamasa** [comment]
Nice catch!

**Comment by wasamasa** [comment]
As I've originally planned for making use of that face for every inactive slot, I haven't diked it out. I hope you're happier with this state of affairs :>
