### ISSUE TITLE
save config between emacs session?

### ISSUE THREAD

**Issue by zeltak** [wasamasa/eyebrowse#46]
Hi!

loving this package (no surprise as im in i3 user ;-). i was wondering how does one save the workspaces between emacs sessions? if its not possible i would like to add a request for that. maybe even loading pre defined workspaces?

thx!

Z

**Comment by wasamasa** [comment]
This feature requires two things to work, saving/restoring window
configurations for all frames and buffers. The former is simple enough, the
latter is tricky to get right. Fortunately desktop-mode provides both, so
enable it and things should just work.

As I don't see any reason to reinvent the wheel, eyebrowse will not have
any code for doing the above on its own. If you wish to have predefined
window configurations, create these programmatically and save/restore the
result.
