### ISSUE TITLE
dosent work in dired?

### ISSUE THREAD

**Issue by zeltak** [wasamasa/eyebrowse#47]
Hi

i would love to use eyebrowse for dired windows but that dosent seem to work in dired (there is no error it just dosent do anything). would that be possible?

thx

Z

**Comment by wasamasa** [comment]
Please provide more details about your Emacs setup (OS, Emacs version,
eyebrowse version) and a minimal reproduction example, like an init.el or
code to be executed in an emacs -Q session.

**Comment by wasamasa** [comment]
Closing due to lack of feedback.
