### ISSUE TITLE
Feature request - support for creating a new slot without specifying which

### ISSUE THREAD

**Issue by peterhoeg** [wasamasa/eyebrowse#48]
Currently we need to use ```C-c C-w number``` to jump to a new slot, but it would be neat if we had a function that simply creates a new slot after the current or last slot.

Example: Imagine you have slots 1 and 2. The idea is to have a shortcut that will create slot 3 without having to care that it's number 3. This would basically emulate :tabnew from vim.

**Comment by wasamasa** [comment]
Thanks for the feature request!

I'd like to copy as much of the behaviour as possible from Vim's `:tabnew` for that one, but am not sure yet about a few things:

- To know where to spawn a new tab, you'll at the very least need to know the current slot.  When would knowing the *last* slot come in handy?  And what kind of last slot is this, the right-most one or the previously active one?  I should really clear up the terminology some day...
- I've played around with Vim a bit.  Pinning the behaviour down should be simple enough, but I don't see how I'm going to support the "numerical" argument preceding the command.  `evil-ex.el` defines a grammar where a range is permitted, so I'll have to look into how that can be extended or changed, possibly involving upstream as well.
- How will this extra argument be represented with Emacs' prefix argument?

**Comment by peterhoeg** [comment]
So ```:tabnew``` inserts a tab after the currently active slot, which means you would need to play around with the numbering, which is probably not a great idea. Another way is to make it configurable so that the user chooses - add to end or add after currently active slot (and then renumber accordingly).

Maybe for a phase 1, just having the possibility to do ```:tabnew``` without the count would be an option?

**Comment by Fuco1** [comment]
Tmux simply opens new tab on smallest available number, which is very expected and intuitive and simple to document behaviour.

You will know the number because it will automatically be the selected one, so you see it on the modeline.  I woudl also very much like this see implemented, often I just want a quick throw-away view and I don't really even care where it goes.

**Comment by Fuco1** [comment]
Re numerical argument, I would not even allow it for this command, what would be the point?

**Comment by wasamasa** [comment]
Opening the tab on the smallest available slot is different from Vim's `:tabnew` which opens them after the current one.  With its interpretation of things, it would make sense to accept a numerical argument to specify what should be considered the current slot.

I've got to admit that your suggested variant is more attractive to me than emulating `:tabnew` as it will deal with "holes" gracefully:

    [1, *2*, 3] -> [1, 2, 3, *4*]
    [1, *3*] -> [1, *2*, 3]

Does this describe the behavior you're envisioning correctly?

**Comment by Fuco1** [comment]
Yep, exactly.  It will fill the holes automatically over time.  My most common workflow is "spawn a new pane/window/config, do some stuff, get rid of it", so it is ideal as I don't have to think about anything.

**Comment by wasamasa** [comment]
I've discovered another corner case:

    [2, *3*] -> [*1*, 2, 3]

That being said, I've implemented your suggestion in the form of a `eyebrowse-create-window-config` command which is bound to `C-c C-w C-c`.  Please confirm that it works as expected, then I can close this issue and take notes for `:tabnew` in my other one about Evil integration.

**Comment by Fuco1** [comment]
I don't see how that is a corner case, it seems consistent with the previously described behaviour.

**Comment by wasamasa** [comment]
In my first implementation of the search for the free slot, I've checked for holes between the first and second, second and third, etc.  That did leave out the possibility that there could be a hole before the first one, hence why I'm considering it another corner case.
