### ISSUE TITLE
eyebrowse--load-window-config crashes emacsclient --tty

### ISSUE THREAD

**Issue by aaronjensen** [wasamasa/eyebrowse#50]
This could be a spacemacs specific issue, as it only happens when `eyebrowse--load-window-config` is called as part of `persp-activated-hook`, but could you please see https://github.com/syl20bnr/spacemacs/issues/5978 to see if you have an idea why this would happen? Thanks!

**Comment by wasamasa** [comment]
I'm not sure whether this is related to eyebrowse at all as I can use it just fine in terminal instances of emacsclient.  What you of course should *not* do is trying to apply a window configuration generated on a graphical frame to a terminal frame as they are incompatible with each other (pixel vs. column sizes mostly)...

**Comment by aaronjensen** [comment]
Yep, that's [exactly what it was](https://github.com/syl20bnr/spacemacs/issues/5978#issuecomment-218487983), it was fixed in spacemacs. Thanks!
