### ISSUE TITLE
side windows become regular windows after swtiching workspace

### ISSUE THREAD

**Issue by bmag** [wasamasa/eyebrowse#52]
Reproduction guide:
- 1. create two workspaces
- 2. in workspace 1, evaluate this code: (e.g. by using `M-:`)
```elisp
(setq mywin (display-buffer (get-buffer-create "buff1") '(display-buffer-in-side-window (side . left) (slot . 0))))
```
buff1 is displayed on the left in a side window.
- 3. evaluate this code: `(window-parameter mywin 'window-side)`  
returned value: `left`
- 4. switch to workspace 2, then switch back to workspace 1
- 5. evaluate this code: `(window-parameter mywin 'window-side)`  
returned value: `nil`, meaning buff1's window is a normal window now, not a side window.
My expectation is that buff1's window should remain a side window.

To be fair, the same result happens if I replace step 4 with this step:
- `M-: (window-state-put (window-state-get mywin t) mywin)`

Changing the value of `window-persistent-parameters` before step 4 solves my issue:
```elisp
(add-to-list 'window-persistent-parameters '(window-side . writable))
(add-to-list 'window-persistent-parameters '(window-slot . writable))
```
I'm not sure why `window-side` and `window-slot` are not persistent by default, there could be a reason I'm not aware of.

I'm mentioning all this because I thought it could be helpful if eyebrowse modified `window-persistent-parameters` accordingly or suggested it as user configuration in the readme.

**Comment by bmag** [comment]
Opened bug report 23858: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23858, lets see how it goes.

**Comment by wasamasa** [comment]
Thank you!

**Comment by wasamasa** [comment]
I've checked again and it appears as if they aren't thrilled of the idea of changing defaults, but Martin Rudalics isn't opposed to enhancing `window-state-get`/`window-state-put` to support all window parameters.

I see a few options for proceeding:
- Wait until this change has been implemented, end up doing nothing (yey)
- Tell users to customize `window-persistent-parameters` in the README (clean solution for the few that care)
- Let-bind `window-persistent-parameters` to an alist containing all the interesting parameters around everything using `window-state-get`/`window-state-put` (would magically work, but ignore a customized variable which sucks)
- Customizing `window-persistent-parameters` for the users (plzno)

As you could probably guess, option 2 sounds best to me.

**Comment by bmag** [comment]
> As you could probably guess, option 2 sounds best to me.

Agreed, that's probably the best.

**Comment by wasamasa** [comment]
Great, I've added a notes section.  For now it only contains this caveat, your provided customization sample and a link to this issue.
