### ISSUE TITLE
Feature Request: remember pages/locations in pdf documents

### ISSUE THREAD

**Issue by YiLiu6240** [wasamasa/eyebrowse#53]
This is related to a issue here: https://github.com/politza/pdf-tools/issues/232

Is it possible to let eyebrowse window configs to remember current pdf pages
in each eyebrowse window config, like switching between different locations in
the same pdf document in several window configs?

**Comment by wasamasa** [comment]
I'm not sure I understand your request.  This package is about saving and restoring *window* configurations.  You're asking for it to save and restore docview/pdf-tools locations per window configuration?

This kind of thing should be possible by using the frame-local storage for window configurations and the package hooks.  I see no reason for implementing it though as it deviates too far from the purpose of this package.
