### ISSUE TITLE
golden-ratio-mode breaks eyebrowse when using multiple windows

### ISSUE THREAD

**Issue by topher200** [wasamasa/eyebrowse#56]
#### Description :octocat:
Creating or moving to a eyebrowse workspace with a complex window arrangement while in golden-ratio-mode results in error.

Turning off golden-ratio-mode removes the error.

Observed on Spacemacs' master and develop.

#### Reproduction guide :beetle:
- Start Emacs
- `C-x b sc Enter` Navigate to \*scratch\* buffer
- `Space t g` Turn on golden-ratio-mode
- `Space w v` Split the window vertically
- `Space w h` Split the window horizontally
- `Space w v` Split the window vertically one more time
- :white_check_mark: There should be four windows
- `C-c C-w C-c` Attempt to create a new workspace

*Observed behaviour:* :eyes: :broken_heart:
The new workspace is created!

However, we stay in our original workspace. One of the windows has disappeared from our original workspace; we now have three windows.

This error appears in the status bar:
`window--state-put-1: Cannot resize window #<window 3 on  *temp*>`

*Expected behaviour:* :heart: :smile:
The new workspace is created. We move to the new workspace. Our original workspace is unmodified.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql auto-completion emacs-lisp
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
     (git :variables git-gutter-use-fringe t)
     go helm html javascript markdown python shell
     (syntax-checking :variables syntax-checking-enable-tooltips nil)
     topher yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by wasamasa** [comment]
I'm sorry, but could you please provide a repro not involving your Emacs configuration, that is, Spacemacs?

**Comment by topher200** [comment]
Steps to reproduce without Spacemacs:

1. Clear out your emacs configuration by deleting or moving your .emacs.d/
1. Start Emacs
1. Enable Marmalade repo (https://marmalade-repo.org/#download)
1. Install eyebrowse using install-package
1. Install el-get (https://github.com/dimitri/el-get)
1. Install golden-ratio-mode using `el-get-install golden-ratio-mode`
1. `M-x eyebrowse-mode` Turn on eyebrowse mode
1. `M-x golden-ratio-mode` Turn on golden-ratio mode
1. `C-x 3` Split window on the right
1. `C-x 2` Split window on the bottom
1. `C-x 3` Split window on the right
1. :white_check_mark: There should be four windows
1. `M-x eyebrowse-create-window-config` Create a new workspace using eyebrowse

Observe this error in \*Messages\*:
`window--state-put-1: Cannot resize window #<window 20 on  *temp*>`

**Comment by wasamasa** [comment]
This should also work by installing everything from MELPA, right?

**Comment by topher200** [comment]
I would assume so! I've had no issues reproducing the issue no matter how the pieces were installed.

**Comment by wasamasa** [comment]
Hmm, I can switch window configurations, but get different errors in a minimal session.  Can you enable backtraces with `M-x toggle-debug-on-error` and include yours?

**Comment by topher200** [comment]
I tried, but no backtrace appears in \*Backtrace\*.

I'm going to modify the steps a bit by adding a step 8B, just so that we start with the exact same window configuration.

1. Clear out your emacs configuration by deleting or moving your .emacs.d/
1. Start Emacs
1. Enable Marmalade repo (https://marmalade-repo.org/#download)
1. Install eyebrowse using install-package
1. Install el-get (https://github.com/dimitri/el-get)
1. Install golden-ratio-mode using `el-get-install golden-ratio-mode`
1. `M-x eyebrowse-mode` Turn on eyebrowse mode
1. `M-x golden-ratio-mode` Turn on golden-ratio mode
  - Step 8B: Close all windows but one using `C-x 0`. Load your `*scratch*` buffer into that window
1. `C-x 3` Split window on the right
1. `C-x 2` Split window on the bottom
1. `C-x 3` Split window on the right
1. :white_check_mark: There should be four windows
1. `M-x eyebrowse-create-window-config` Create a new workspace using eyebrowse

Here's what I get in \*Messages\* with that configuration:
```
Debug on Error enabled globally
window--state-put-1: Cannot resize window #<window 56 on  *temp*>
```
Notice that \*Messages\* says that I've enabled debug-on-error, but there is no \*Backtrace\* buffer.

**Comment by topher200** [comment]
@wasamasa If it would be helpful to do some kind of screenshare to debug the issue together I'd be happy to assist.

**Comment by wasamasa** [comment]
OK, can reproduce that one now.  I have a partial fix that defers the error to happen a bit later.  From what I can tell, golden-ratio does really weird things.  One part is advicing/hooking nilly-willy, the other part is resizing windows shortly after the user performed a command (which is too late for packages to notice)

**Comment by wasamasa** [comment]
I have the other "fix".  If you remove the part of `golden-ratio-mode` that adds itself to `window-configuration-change-hook`, the error is no more.  Therefore I consider this to be a golden-ratio-mode issue.  Still, thanks for pointing this one out as I've made eyebrowse a bit more robust after the suggestion!

**Comment by ChrisSalisbury** [comment]
In case anyone else is having this problem, this pull request seems to solve the problem for me:  https://github.com/roman/golden-ratio.el/pull/66

I have only tested in two workspaces that I am using right now so far, so caveat emptor.

**Comment by llcc** [comment]
Hi, i profiled the function invoking by enabling `golden-ratio`, i got results below that seems like `eyebrowse-format-slot` in `eyebrowse-mode-line-indicator` calls the golden-ratio functions.

I don't know if this can help but i hope/

![image](https://user-images.githubusercontent.com/3996879/47780149-2a2b6d00-dd3e-11e8-9822-3da98f965e8a.png)

**Comment by wasamasa** [comment]
Please don't hijack existing threads for unrelated problems. Besides, I fail seeing what the problem is. All the profiler log shows here is that when windows are resized, both the eyebrowse indicator is recalculated and golden-ratio resizing is triggered as well. If you have an issue with golden-ratio triggering too often, complain on their bug tracker, not here.

**Comment by llcc** [comment]
Sorry for that. Will issue one there. I can delete this one if it is needed.

**Comment by eubarbosa** [comment]
Yep, not fixed!
