### ISSUE TITLE
feature requests: save to disk and ido session name matching

### ISSUE THREAD

**Issue by notuntoward** [wasamasa/eyebrowse#59]
This is nice.  A couple feature requests:

1. Save the window configurations to disk, so can reuse them like, say, recentf
2. use the names when switching between configurations, ideally like ido does between buffers

**Comment by wasamasa** [comment]
1. Deliberately omitted, use desktop.el or alike for persistence. 
2. The name is already displayed for tagged window configurations and should be included in the switching command because both use the same formatting helper.
