### ISSUE TITLE
Eyebrowse not showing up in powerline

### ISSUE THREAD

**Issue by technician77** [wasamasa/eyebrowse#60]
Do I need to set a special variable to make it visible in powerline? I've opened an issue in powerlines github repo but the author doesn't seem to have an idea. Could you give him an info/clue to solve the problem? I have no idea about coding so I can't be much of help.

The issue is accessible via: [https://github.com/milkypostman/powerline/issues/140](https://github.com/milkypostman/powerline/issues/140)

**Comment by wasamasa** [comment]
No, you need to fix powerline.  I'm using smart-mode-line myself as it tries hard to display all modeline information available and doesn't have that issue.
