### ISSUE TITLE
saving window configs using desktop-save-mode

### ISSUE THREAD

**Issue by technician77** [wasamasa/eyebrowse#61]
Did I understand correctly that when I set `(desktop-save-mode 1)` then the window configs should be saved in the .desktop file, right?
My desktop is saved and restored via desktop-save-mode, but the window config is gone. Is there a step that I'm missing?

![image](https://user-images.githubusercontent.com/18722291/27011940-ff8ee2ae-4ec6-11e7-8c50-73a8683a1565.png)
After restore:
![image](https://user-images.githubusercontent.com/18722291/27011962-69790348-4ec7-11e7-8c52-39dfc3bb6584.png)

It's not a display problem of powerline (anymore), as you can see in pure modeline, the window configs are not restored:
![image](https://user-images.githubusercontent.com/18722291/27011978-ab8ae5f8-4ec7-11e7-87da-fd7aa2b2a508.png)

Would you agree that ivy-views is an alternative? If so you might mention it in the readme. For the moment I use it as a workaround to save window configs.

**Comment by wasamasa** [comment]
What Emacs version are you on?  Window configurations are stored in the frame, `desktop.el` only supports restoring such variables as of Emacs 24.4.

I haven't tested out ivy much and searching for ivy-views on the web gives me porn and gardening results.  I'm open to adding it to the README though.

**Comment by technician77** [comment]
I use GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24.

You haven't? Ivy is great in all regards. You need to install ivy/counsel/swiper packages to harness all the power. There are also quite some third party counsel-XXX packages. In a sense it's quite similar to helm, but ivy is minibuffer centric while helm is buffer centric. To me it feels much more native than helm, but ultimately it's a matter of taste I think.

You need to search for "ivy views emacs" in google but here are the links
Ivy was a part of swiper, but they are now separate packages but on github they still seem to be combined: 
[https://github.com/abo-abo/swiper](https://github.com/abo-abo/swiper)
Here is the article on ivy-views:
[https://oremacs.com/2016/06/27/ivy-push-view/](https://oremacs.com/2016/06/27/ivy-push-view/)

**Comment by notuntoward** [comment]
I just checked those articles but don't see a way to persistently store ivy-views-- getting them back after restarting emacs.  Has someone written and ivy addon that does this kind of desktop configuration saving?  Also, does it handle indirect buffers?

**Comment by wasamasa** [comment]
Yes, but I don't see how I can be of any help there.  Therefore I'm closing this.

**Comment by mpettigr** [comment]
To persistently store ivy-views, you can use desktop-save-mode and save the variable.
