### ISSUE TITLE
Eyebrowse should remember window parameters

### ISSUE THREAD

**Issue by Alexander-Miller** [wasamasa/eyebrowse#64]
As of now switching eyebrowse desktops gets rid of custom window parameters. This can lead to wrong behaviour in other packages, when, for example, a desktop switch leads to a window losing its side-window status, meaning it now gets killed by delete-other-windows, or disappears when calling magit-status.

For a simple example use this code:
```
(display-buffer-in-side-window 
 (get-buffer-create "test")
 '((side . left)
   (window-parameters . ((no-delete-other-window . t)))))

(global-set-key (kbd "C-x C-m")
 (lambda () (interactive) (message "%s" (window-parameters (selected-window)))))
```
Using that keybind in the created window has the following output:
`((no-delete-other-window . t) (quit-restore window window #<window 3 on *scratch*> test) (window-slot . 0) (window-side . left))`
And after switching eyebrowse view and back:
`((window-slot . 0) (window-side . left))`

**Comment by wasamasa** [comment]
I added code to ignore window parameters when saving a window configuration as it made it impossible to apply it elsewhere otherwise (IIRC it was only side windows).  To solve this issue you'd need to do one of the following:

- influence window configuration saving/restoring to not run into errors due to window parameters
- apply window configuration without window parameters, restore them afterwards
- get the respective functions fixed and backport the fix somehow

**Comment by Alexander-Miller** [comment]
>  it made it impossible to apply it elsewhere otherwise

Can you tell me more about that part? I looked at the window-configs param and it's storing a hefty alist. Where would the trouble come from if we include window parameters in there?

And assuming that a general solution can't be found, what about a specific one? Is there some point in eyebrowse I can hook myself into, given that the window I want restored with parameters intact can easily be identified via major-mode and buffer-name?

**Comment by Alexander-Miller** [comment]
Ok, I played around some more, and just sticking `'(no-delete-other-window . writable)` into `window-persistent-parameters` seems to give me what I want. 

That was a suspiciously easy find, so can I assume there's something wrong with doing it like that?

**Comment by wasamasa** [comment]
It's a workaround for you, not a general solution to this ticket.

**Comment by Alexander-Miller** [comment]
A workaround for myself and a package of mine is what I've been looking for. A general solution would've been nice, but I'll take what I can get. Having looked around the eyebrowse codebase now the post switch hook is really all I need to make things work on my end.
