### ISSUE TITLE
How to make meta key as prefix?

### ISSUE THREAD

**Issue by rieje** [wasamasa/eyebrowse#65]
How to make meta key as prefix? I have 

    (use-package eyebrowse
      :init
      (setq eyebrowse-keymap-prefix "M") 
      :config
      (eyebrowse-mode t))

But "M-1" doesn't create a workspace.

**Comment by wasamasa** [comment]
Meta is a modifier, not a prefix key.  You'll have to manually create the keybinds yourself, similar to what the `eyebrowse-setup-opinionated-keys` function does.
