### ISSUE TITLE
don't format slot in eyebrowse--read-slot

### ISSUE THREAD

**Issue by blaenk** [wasamasa/eyebrowse#66]
As crazy as it may sound, I wanted to set my `eyebrowse-tagged-slot-format` to something like `" %s "` (notice the padding; I specifically put it here instead of in the separator setting because I want the face to apply to the padding as well), that is, don't show the tag name in the mode-line. This saves space and provides uniform, consistent width for each config indicator. I still do want to use tag names, and the way I can "view" them is via `eyebrowse-switch-to-window-config`. This works very well.

Except that `eyebrowse--read-slot`, which is used by `eyebrowse-switch-to-window-config`, _also_ uses the format settings to format the candidates, which means that I can't format the way I want it to appear in the mode-line separate from the way it shows up in the `--read-slot` function. That is, if I set it to never show the tag name, i.e. to `" %s "`, then it also will never show the tag name when I use `eyebrowse-switch-to-window-config`.

Personally I feel like `eyebrowse--read-slot` should just define local bindings to the defaults: `"%s"` and `"%s:%t"` for non-tagged and tagged respectively.

I'm currently working around this by doing that (local let-bindings) around my call to the mode-line-indicator function, but I figured I'd bring this up for discussion.

**Comment by wasamasa** [comment]
Sorry, but no.  I'm glad you like eyebrowse despite your needs, but this reminds me too much of https://xkcd.com/1172/ to consider implementing it.  Feel free to fork if you disagree.

**Comment by blaenk** [comment]
> Feel free to fork if you disagree.

The issue was not at all meant to convey that I was demanding that you do things the way I expect them to be. I realize now the title may come off that way, sorry, I was just in a rush and couldn't think of a better one. I was merely bringing it up for discussion, fully open to the idea that I was thinking about it the wrong way. In that context it seems silly and unwarranted to imply via xkcd that I am so adamant and entitled about it that I should fork over it. As I mentioned, I'm already working around this just fine, so fair enough.

**Comment by wasamasa** [comment]
I don't see anything to discuss here, hence why I'm suggesting you to fork because I can't see myself going out of my way to support your usecase.
