### ISSUE TITLE
Feature Request: Animated GIF Screenshots

### ISSUE THREAD

**Issue by joelnz** [wasamasa/eyebrowse#69]
I'd love to programatically generate short animated gifs of scenes.
Would be very useful as thumbnails in a gallery.

**Comment by wasamasa** [comment]
Sure, go ahead, ideally with a description what exactly you're looking at.  I've considered the idea, but postponed it for being too much work for a vague goal.

**Comment by wasamasa** [comment]
Closed in favor of #42 due to inactivity
