### ISSUE TITLE
UX: Option to show eyebrowse info earlier on the mode-line to avoid truncation

### ISSUE THREAD

**Issue by xdl** [wasamasa/eyebrowse#78]
Would it be possible to have an option to show the window configuration earlier on in the mode line to avoid truncation? I often have vertically split buffers open for each workspace, so the mode line misc info content gets cut off and I can't see which workspace I'm on.

For context, I'm coming from a tmux/vim workflow where the tmux window number and name is always displayed with the current one highlighted in another line, but not sure if this is possible (multiline mode lines) is easily possible in Emacs.

**Comment by wasamasa** [comment]
That would result in an arms race with Evil, Circe and who knows what else, I intentionally picked `mode-line-misc-info` because hardly anything uses it.

There are no multiline modelines in Emacs. You'd have to replace the modeline with an image to fake this.
