### ISSUE TITLE
Feature Request: Add an option to automatically reorder workspaces

### ISSUE THREAD

**Issue by vxid** [wasamasa/eyebrowse#80]
It would be nice to have an option to automatically reorder workspaces when closing one.

For instance, if I have workspaces [1,2,3], closing the second one results in [1,3] instead of [1,2], which is confusing when only jumping to workspaces using their numbers. I think programs like tmux have this behavior by default.

**Comment by wasamasa** [comment]
tmux doesn't actually. I can see this feature to be confusing as well, so I'll close it for now until someone shows a program actually doing this.

**Comment by vxid** [comment]
I ended up writing a function to take care of reordering workspaces. No need to add an option to automatically do that then.

``` elisp
(defun reorder-eyebrowse-workspaces ()
  (let* ((window-configs (eyebrowse--get 'window-configs))
         (counter 0)
         (len (length window-configs)))
    (while (< counter len)
      (setf (car (nth counter window-configs)) (+ counter 1))
      (setq counter (1+ counter)))))

```
