### ISSUE TITLE
Wrong type arguement: hashtable p: unprintable entity

### ISSUE THREAD

**Issue by ibnishak** [wasamasa/eyebrowse#81]
Error when trying to use in Ubuntu 17.10
Emacs 25.3.

Any other log needed?

**Comment by wasamasa** [comment]
Yes. I have absolutely no idea why this would happen with this much information. Please provide a full backtrace after running `M-x toggle-debug-on-error` and reproducing the error.

**Comment by wasamasa** [comment]
I guess I won't get any more info on this.
