### ISSUE TITLE
Support unicode icon in tag name

### ISSUE THREAD

**Issue by azzamsa** [wasamasa/eyebrowse#82]
I think I need to add some code to have this ability. Since I need to specify the workspace number then the "unicode string". Then switching workspace with number.

![2018-05-07-11 51 45](https://user-images.githubusercontent.com/17734314/39685572-b6bc5b3a-51ed-11e8-97d7-a0be1d9c669c.png)

But when I tried to put unicode string in tag name immediately. It works. I think because yebrowse still *access* them with number when I invoke `C-c C-w <num>` rather than tags.

![2018-05-07-11 51 27](https://user-images.githubusercontent.com/17734314/39685604-f8b6430c-51ed-11e8-96c8-4d2288a7b2b3.png)
![2018-05-07-11 51 27](https://user-images.githubusercontent.com/17734314/39685609-ff3aa4e8-51ed-11e8-8ba1-70ba4a1d89ee.png)

PS: *the unicode icon broken in active workspace, but I am okay with that. it also easy to spot what workspace is active*

Thanks lot for eyebrowse.

**Comment by azzamsa** [comment]
Thanks for your contribution to community.

**Comment by wasamasa** [comment]
I don't get it. Is there an issue or not? I doubt there is anything Eyebrowse can do about how unicode is displayed in Emacs, it's just some code to manage windows. Your display glitch looks like there's no bold version of the unicode glyph you use, feel free to customize the `eyebrowse-mode-line-active` face.

**Comment by azzamsa** [comment]
> Is there an issue or not?

No there is no issue. I put it here just to tell newcomers if they want to open an issue. Asking if they can put unicode string in eyebrowse tag.

**Comment by azzamsa** [comment]
> Your display glitch looks like there's no bold version of the unicode glyph you use, feel free to customize the eyebrowse-mode-line-active face.

aha. Thanks. :)
