### ISSUE TITLE
Alternative keybinding recommendation

### ISSUE THREAD

**Issue by azzamsa** [wasamasa/eyebrowse#84]
For die hard org-mode user. Eyebrowse will conflict with org-refill which bound to (`C-c C-w`) too.

Any recommendation for Eyebrowse alternative keybinding ?
Or it's better to warn in Readme that default keybinding will conflict with org refill.

Thanks for Eyebrowse.

**Comment by wasamasa** [comment]
It turns out I already did this in the README. I've added a clarification on it.

**Comment by azzamsa** [comment]
>No recommendation here because I use only a few Org keybindings and use the shorthands. I suspect that all C-c C-<letter> combinations are taken by Org already...

That's true

I changed the keymap prefix to `C-c M-e` but it takes too long to press. Then I use key chord. Which is very fast and handy with the capability of `eyebrowse-switch-back-and-forth`

``` elisp
(use-package eyebrowse
  :ensure t
  :defer 1
  :init
  (setq eyebrowse-keymap-prefix (kbd "C-c M-e"))
  (global-unset-key (kbd "C-c C-w"))
  :chords (";e" . eyebrowse-last-window-config)
  :config
  (eyebrowse-mode t)
  :custom
  (eyebrowse-switch-back-and-forth t)
  (eyebrowse-new-workspace t))
```

Thanks for Eyebrowse :)

**Comment by rnwolf** [comment]
Hello. I am learning how to use emacs via spacemacs in order to use org-mode. The default spacemacs config has bound C-c C-w to eyebrowse. I tried azzamsa suggestion in defun dotspacemacs/user-config () section of .spacemacs but it has not worked. Any tips on where I specify the updated keybinding?

**Comment by azzamsa** [comment]
> Any tips on where I specify the updated keybinding?

unfortunately. I never use spacemacs. But `use-package` is only macros over manual configuration.

The important lines are both
``` elisp
  (setq eyebrowse-keymap-prefix (kbd "C-c M-e"))
  (global-unset-key (kbd "C-c C-w"))
```

The first set your prefix-key for eyebrowse. Then the second unset the default key.

If you can't make it work (this is because your manual config not laoded before eyebrowse. You have to put it before eyebrowse load) see https://github.com/wasamasa/eyebrowse/issues/49#issuecomment-214900621. I suggest enabling `Eyebrowse Switch Back And Forth` in `M-x customize-mode` then choose `eyebrowse-mode`. Then put this somewhere in your config.

``` elisp
(global-set-key (kbd "C-\"") 'eyebrowse-last-window-config)
```

Then you don't need a prefix key to switch back and fort to your window config. You can use `C-"` or any key you like.

Hope it help.
