### ISSUE TITLE
Automatically adjust tag number?

### ISSUE THREAD

**Issue by yanghaoxie** [wasamasa/eyebrowse#85]
I am going to use an example to illustrate this.

Suppose I have three tags `[1, 2, 3]`, when I delete tag `2`, it will become `[1, 3]`; therefore, when I am using `eyebrowse-switch-to-window-config-<#>`, I have to using `1` and `3`, which is kind of inconvenient.

So, is it possible to automatically adjust tags, in this example, when I delete `2` from `[1, 2, 3]`, the tags will become `[1, 2]`, and the `window config` in `3` will be moved to `2` automatically.

**Comment by wasamasa** [comment]
No.
