### ISSUE TITLE
How to get all window configs in list or similar format?

### ISSUE THREAD

**Issue by JJPandari** [wasamasa/eyebrowse#87]
I'm thinking that displaying the window config numbers and tags in the mode line consumes too much mode line space (when I've tagged 2 or 3 configs), so it may be a good idea to not show the mode line indicator, and use completion frameworks like [ivy/swiper](https://github.com/abo-abo/swiper/) to let me search through the configs by tag names when I don't remember which is which.  

So I'd like to know the way to get all window configs in a list like `((1 . "org") (2 . "work"))`, which basically contains the number and tag for each config. When this is done, I can search through them, pick one, and `eyebrowse-switch-to-window-config` the picked config number.  

Is it sensible to make this a public variable?

**Comment by wasamasa** [comment]
Why not customize `eyebrowse-mode-line-style` to `hide` and use `eyebrowse-switch-to-window-config` and ivy's completing-read replacement?  I don't see why there would be any variable whatsoever.  In case you really need to write your own command, there's `eyebrowse--get`, check the source code to get an idea how window configs are retrieved.

**Comment by JJPandari** [comment]
I missed the vital `eyebrowse-switch-to-window-config` command when configuring my key bindings, because I copied (what I thought to be) "available commands" from the [key bindings](https://github.com/wasamasa/eyebrowse#key-bindings) section in README, and you missed out this command there. How about add it there? In case my story happens to some noob like me XD.

**Comment by wasamasa** [comment]
It isn't listed there because there's no key binding for it.
