### ISSUE TITLE
Can I save my eyebrowse layouts in a more permanent fashion?

### ISSUE THREAD

**Issue by mrbig033** [wasamasa/eyebrowse#90]
I was using desktop-save, but Emacs mess it up from time to time.

**Comment by wasamasa** [comment]
Saving window configurations is deliberately not part of this package. If desktop.el doesn't work for you, find something else (and don't forget reporting about how it went).

**Comment by mrbig033** [comment]
I didn't understand your previous response, so I'm answering it again to clarify. `desktop-save` works most of the time, but it eventually messes up, and I'd really like to keep all my layouts with their custom names that I made for them. I totally understand that this is not the focus of eyebrowse. I'll look into other solutions and report back. [desktop-plus](https://github.com/ffevotte/desktop-plus) seems interesting. Thanks!

**Comment by mrbig033** [comment]
I couldn't find a package that did what I wanted, so I created an `eyebrowse` directory to backup my layouts, and a bash alias to easily overwrite the emacs desktop files whenever it messes up. In the future, I can embed this restore functionality on Emacs itself.

**Comment by mrbig033** [comment]
Okay! [bookmark+](https://www.emacswiki.org/emacs/BookmarkPlus) have a helpful command that saves a copy of the desktop and binds a bookmark.: `bmkp-set-desktop-bookmark`. It's annoying that Emacs starts saving the desktop in the new file, which misses the point in my opinion. But that can be customized.
