### ISSUE TITLE
Is there a way to set up pre-organized workspaces?

### ISSUE THREAD

**Issue by jonnycyr** [wasamasa/eyebrowse#91]
I often have the same workspaces whenever I work in Emacs - is there a way to set it up so that when I open a workspace it will have the buffers that I want? For example, I have a tasks workspace that is split into 4 frames with the buffers someday.org, next_actions.org, projects.org, and inbox.org.

**Comment by wasamasa** [comment]
There isn't, no. You could use desktop.el to save and restore your last state though.
