### ISSUE TITLE
Disabling eyebrowse-mode does not remove win config indicators in the status bar 

### ISSUE THREAD

**Issue by srustamo** [wasamasa/eyebrowse#93]
GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.6.0, Carbon Version 158 AppKit 1561.4) of 2018-06-04

With basic config:

(use-package eyebrowse
  :config
  (eyebrowse-mode))

Creating a second config with C-c-w 2 shows [1, 2] in the status line. 

Disablign the mode with M-x (eybrowse-mode), disables the mode, but does not remove the [1, 2] from status line.

Also, if (eyebrowse-setup-opinionated-keys) is used, after disabling the mode the evil keybindings introduced by this package linger behind.

**Comment by wasamasa** [comment]
Sorry, but I won't fix this. Generally, there is no need to disable the mode unless you're experimenting and found it's not to your needs (in which case, remove the customizations and package and restart Emacs). It's a global minor mode after all.
