### ISSUE TITLE
Defect: can't use it when point is on a markdown buffer

### ISSUE THREAD

**Issue by Trevoke** [wasamasa/eyebrowse#95]
This is what happens when I hit `C-c C-w` on a buffer that's using https://jblevins.org/projects/markdown-mode/ 

> let: Wrong type argument: commandp, (keymap (3 . eyebrowse-create-window-config) (99 . eyebrowse-create-window-config) (57 . eyebrowse-switch-to-window-config-9) (56 . eyebrowse-switch-to-window-config-8) (55 . eyebrowse-switch-to-window-config-7) (54 . eyebrowse-switch-to-window-config-6) (53 . eyebrowse-switch-to-window-config-5) (52 . eyebrowse-switch-to-window-config-4) (51 . eyebrowse-switch-to-window-config-3) ...)

**Comment by wasamasa** [comment]
`C-c C-w` is a prefix, not a full command. That aside, I cannot reproduce this with `C-c C-w 0` or alike. Chances are you screwed something up in your config.

**Comment by Trevoke** [comment]
Thanks for the help. I found the problem, and it's unrelated to both
markdown-mode and my config.
