### ISSUE TITLE
New workspaces with *Scratch* as default buffer

### ISSUE THREAD

**Issue by eubarbosa** [wasamasa/eyebrowse#98]
Hi,

Its probably possible achievable with add-advice...

Still,  I think most users would expect eyebrowse workspaces to behave like DE/WM newly created workspaces with wallpaper as its background.

Just a humble feedback!  :+1:

**Comment by wasamasa** [comment]
This is a duplicate of #23

**Comment by eubarbosa** [comment]
LOL, I beg your pardon! Thanks!
